### ISSUE TITLE
Why are you using a framework?

### ISSUE THREAD

**Issue by TesDevelopment** [JakeHolcroft/lipsum#1]
Just use HTML?!???!?!?!?!?!?!

**Comment by JakeHolcroft** [comment]
Vercel free hosting and was an early project for me to learn the next project layout  👍 why are you playing roblox?

**Comment by TesDevelopment** [comment]
I've never touched roblox

**Comment by RuadhanKM** [comment]
bro got exposed 💀

**Comment by TesDevelopment** [comment]
:(
